# Generated by Django 2.1.5 on 2024-12-03 19:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genaral_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheTruth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
