# Generated by Django 2.1 on 2024-10-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genaral_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
