# Generated by Django 5.1.2 on 2024-10-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genaral_news', '0002_news_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
